# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/582f84d3-15ef-477c-9d78-f12d895cbeee";
      fsType = "btrfs";
      options = [ "subvol=@" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/582f84d3-15ef-477c-9d78-f12d895cbeee";
      fsType = "btrfs";
      options = [ "subvol=@var" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/162E-2B4C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/32ce1893-95be-4f9e-8cf8-fde9b144844d";
      fsType = "btrfs";
      options = [ "subvol=@home" "defaults" "noatime" "space_cache=v2" "discard=async" "compress=zstd" "ssd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/796a03b9-2659-4894-bf8c-c73d504be598"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
