#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
  type = 'os'
  foreground = 'p:os'
  style = 'plain'
  template = '{{.Icon}}'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .UserName }}@{{ .HostName }} '
